### ISSUE TITLE
What is hangouts call center?

### ISSUE THREAD

**Issue by Thinkscape** [pdxjohnny/hangouts-caller#1]
Hey Johnny.

My google-fu failed to answer the question of what is google hangouts call center. Is that some kind of proxy daemon? Is that some host that google owns? Where can I find it ?

**Comment by Thinkscape** [comment]
Ah, sorry. Found it.

https://github.com/pdxjohnny/hangouts-call-center

**Comment by johnandersen777** [comment]
Hahaha, sorry I never documented this but its pretty cool if you put the time into figure out what I did. It's a server that listens for requests (call center) and spins up containers running firefox that get VNC automated to click where it needs to in order to make hangouts.google.com call a phone number.
